---
- name: 1.Installation Apache
  yum: pkg=httpd state=latest
- name: 2.Installation PHP
  yum: pkg=php state=latest
- name: 3.Installation extension PHP
  yum: pkg={{ item }} state=latest
  with_items:
   - php-mysql
   - php-soap
   - php
   - php-pear
- name: 4.Installation de MariaDB   
  yum: pkg={{ item }} state=latest
  with_items:
    - mariadb
    - mariadb-server
- name: 5.Started the dns server service   
  service: name=named state=started
- name: 6.Start Apache Service   
  service: name=httpd state=started enabled=yes
- name: 7.Start MariaDB service   
  service: name=mariadb state=started enabled=yes 
- name: 7.Start firewalld service   
  service: name=firewalld state=started enabled=yes 
- name: 8.Add firewall rule   
  action: command {{ item }} 
  with_items:
      - /usr/bin/firewall-cmd --permanent --add-port=80/tcp 
      - /usr/bin/firewall-cmd --permanent --add-port=443/tcp
      - /usr/bin/firewall-cmd --permanent --add-port=53/tcp 
      - /usr/bin/firewall-cmd --permanent --add-port=53/udp 
      - /sbin/iptables -A INPUT -p tcp -m tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT
      - /sbin/named-checkconf /etc/named.conf
- name: Copy application code to document root  
  template: src={{item.src}} dest={{item.dest}}
  with_items:
    -  { src: 'roles/LAMPSERVER/templates/named.conf.j2', dest: '/etc/named.conf'} 
    -  { src: 'roles/LAMPSERVER/templates/ansible.test.zone.j2', dest: '/var/named/ansible.test.zone'}
    -  { src: 'roles/LAMPSERVER/templates/254.168.192.rev.j2', dest: '/var/named/254.168.192.rev'}
  notify: 
      - restart named
      - restart firewalld
